name: git-secrets

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets
          sudo make install
      - name: Install rules
        run: git-secrets/git-secrets --register-aws
      - name: Scan history
        run: git-secrets/git-secrets --scan --recusrsive
